### PR TITLE
Move files to dtoa subdirectory

### PR DESCRIPTION
**Pull request by mikekaganski**
... since that directory is required by the #includes. Having the
subdirectory in the project allows to have correct file structure
right after untaring, and put the directory where untaring happens
into the project's include directories.

### CODE REVIEW

**Comment by achan001** [comment]
@mikekaganski , I move the files to directory dtoa.
Also, I created a version number, 1.0, for this.
Any major changes to the code will bump out the version numbers.

**Comment by mikekaganski** [comment]
I suppose more changes are needed before v1:

1. Change all files that are to be included into other files to be .h;
2. Create "include" directory with interface headers - i.e., the minimal set of definitions to use the library by clients;
3. Cleanup dependencies, to avoid having dtoa files in mapm, and only use interface headers from mapm;
4. maybe more...

**Comment by mikekaganski** [comment]
Looks like you forgot dtoa/strtod-fast.c when manually moved file (why? it could be easier to just accept and merge the PR?)

**Comment by achan001** [comment]
```
Looks like you forgot dtoa/strtod-fast.c when manually moved file 
(why? it could be easier to just accept and merge the PR?)
```
Everything is here in dtoa, total **18 files**, same as my laptop.

Since I have not update the files for a while, I upload them directly from my laptop.
(just to sync with what I actually had)

**Comment by mikekaganski** [comment]
Ah yes, excuse me, was playing with my makefile and forgot to revert its changes for the new fileset.

**Comment by achan001** [comment]
@mikekaganski , I have no clue how to resolve conflict for a zipped file.

Is it OK if you cancel and re-fork the project ?

**Comment by mikekaganski** [comment]
Of course! No problem.

**Pull request closed without merging**
